# Generated by Django 5.2.7 on 2026-01-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_orderitem_address_orderitem_order_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash on Delivery')], default='UPI', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
