# Generated by Django 5.2.7 on 2026-02-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_productvariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
